### ISSUE TITLE
Install on debian fails after new proxmox update

### ISSUE THREAD

**Issue by insanebaba** [mawalu/wireguard-private-networking#22]
Getting error message after new update 
`
{"msg": "The conditional check 'is_proxmox.stat.exists' failed. The error was: error while evaluating conditional (is_proxmox.stat.exists): 'dict object' has no attribute 'stat'\n\nThe error appears to be in '/home/<user>/.ansible/roles/mawalu.wireguard_private_networking/tasks/main.yml': line 24, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install linux headers when debian proxmox\n  ^ here\n"}`

**Comment by mawalu** [comment]
Thanks for reporting, this seems to be caused by #21. Can you check again with the current master branch, the change should not matter because you are on Debian but I don't have any other ideas what could cause this at the moment

**Comment by fgierlinger** [comment]
I encountered the exact same error while trying to configure 2 CentoOS8 server. Using the master branch did fix the error for me and the role could execute without an error.

**Comment by mawalu** [comment]
Okay thanks for testing. I will tag a new release
